modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Library%3A%20Spawn%20A%20Mob%20%28SAM%29"

[[mods]]
modId="samlibrary"
version="0.1"
displayName="SAM Library"
displayURL="https://minecraft.curseforge.com/projects/sam-library"
authors="Rick South"
description="The Spawn A Mob Library assists in efficiently changing and adding mob spawns."

[[dependencies.samlibrary]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.samlibrary]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"